package comments;
// Generated 20-Dec-2015 19:30:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private String user;
     private String text;

    public Comments() {
    }

    public Comments(String user, String text, Date timestamp) {
       this.user = user;
       this.text = text;
       this.timestamp = timestamp;
    }
   public Comments( int commentId
     , String user
     , String text
     , Date timestamp) {
       this.id = commentId;
       this.user = user;
       this.text = text;
       this.timestamp = timestamp;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
    
}


