package products;
// Generated 20-Dec-2015 19:30:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Date timestamp;
     private String user;
     private String store;
     private String goods;

    public Orders() {
    }

    public Orders(String user, String store, String goods, Date timestamp) {
       this.user = user;
       this.store = store;
       this.goods = goods;
       this.timestamp = timestamp;
    }
    public Orders(Orders ords) {
       this.user = ords.user;
       this.store = ords.store;
       this.goods = ords.goods;
       this.orderId = ords.orderId;
       this.timestamp = ords.timestamp;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getStore() {
        return store;
    }

    public void setStore(String store) {
        this.store = store;
    }

    public String getGoods() {
        return goods;
    }

    public void setGoods(String goods) {
        this.goods = goods;
    }
    
}


